site_name: 我的电子书
site_description: 使用 MkDocs 和 GitHub 创建的电子书
site_author: 作者名称

# 配置主题
theme:
  name: 'readthedocs'

# 导航结构
nav:
  - 首页: index.md
  - 第一章: chapter1.md
  - 第二章: chapter2.md
  - 关于: about.md

# GitHub 仓库链接
repo_url: https://github.com/qiuzefan/ebook

# 版权信息
copyright: 'Copyright &copy; 2025'

# GitHub Pages 部署配置
site_url: https://qiuzefan.github.io/ebook/